---
version: '3.8'
services:
  mysql:
    image: 'mysql:8.0.31'
    restart: always
    env_file: ./compose.env
    networks:
      - backend
    volumes:
      - mysql-vol:/var/lib/mysql
  nginx:
    hostname: nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api
      - client
    restart: always
    image: "tomersf/bynet-nginx:${BUILD_NUMBER}"
    networks:
      - frontend
      - backend
    ports:
      - '80:80'
  api:
    hostname: api
    image: "tomersf/bynet-api:${BUILD_NUMBER}"
    networks:
      - backend
    env_file: ./compose.env
    command: sh -c '/app/wait-for.sh mysql:3306 -- flask run'
    volumes:
      - './wait-for.sh:/app/wait-for.sh'
    depends_on:
      - mysql
    ports:
      - "5000-5001:5000"
  client:
    hostname: client
    image: "tomersf/bynet-client:${BUILD_NUMBER}"
    networks:
      - frontend
    environment:
      - WDS_SOCKET_PORT=0
    ports:
      - "3000-3001:3000"

networks:
  frontend:
    external: true
  backend:
   external: true
volumes:
  mysql-vol:
    external: true
